name: Source Code CI
on:
  push:
    branches:
    - feature/*
jobs:
  ci:
    runs-on: ubuntu-latest
    stpes:
    - name: Checkout Code
      uses: actions/checkout@v5
     
    - name: Setup node.js
      uses: actions/setup-node@v5
      with:
        node-version: "22.19.0"
    
    - name: Indatll Dependencies
      run: npm ci
      
    - name: Run Linting
      run: npm run lint